active_pipelines: ["image_pipeline_dynamic", "video_pipeline_dynamic", "video_pipeline_dynamic_v3", "image_pipeline_dynamic_v3", "image_pipeline_face_embeddings_v1", "video_pipeline_face_recognition_v1"]
default_image_pipeline: "image_pipeline_dynamic"
default_video_pipeline: "video_pipeline_dynamic"
loglevel: "INFO"
port: 8000