active_pipelines:
- video_pipeline_dynamic_v3
- image_pipeline_dynamic_v3
- image_pipeline_dynamic_v4
- video_pipeline_dynamic_v4
- audio_pipeline_v4
default_image_pipeline: image_pipeline_dynamic_v4
default_video_pipeline: video_pipeline_dynamic_v4
default_audio_pipeline: audio_pipeline_v4
loglevel: INFO
port: 8000
