image_pipeline_dynamic_v4:
  full_image_models: ALL
  detector_models:
    - capabilities: [detection]
      categories: [face_detections]
  region_models:
    - detector:
        capabilities: [detection]
        categories: [face_detections]
      models:
        - capabilities: [embedding]
          categories: [face_embeddings]
          scopes: [region]
video_pipeline_dynamic_v4:
  full_image_models: ALL
  detector_models:
    - capabilities: [detection]
      categories: [face_detections]
  region_models:
    - detector:
        capabilities: [detection]
        categories: [face_detections]
      models:
        - capabilities: [embedding]
          categories: [face_embeddings]
          scopes: [region]
audio_pipeline_v4:
  audio_models: ALL
